-- MySQL Script generated by MySQL Workbench
-- sam. 22 août 2020 01:33:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Farm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Farm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Farm` DEFAULT CHARACTER SET utf8 ;
USE `Farm` ;

-- -----------------------------------------------------
-- Table `Farm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farm`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Farm`.`farms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farm`.`farms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `localisation` VARCHAR(45) NULL,
  `set_date` DATE NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_farms_users1_idx` (`user_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Farm`.`fills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farm`.`fills` (
  `id` INT NOT NULL,
  `farm_id` INT NULL,
  `date` DATE NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fills_farms_idx` (`farm_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Farm`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farm`.`food` (
  `id` INT NOT NULL,
  `stock` INT NULL,
  `daily_consumption` INT NULL,
  `total_consumption` INT NULL,
  `need_consumption` INT NULL,
  `index_consumption` FLOAT NULL,
  `entry_date` DATE NULL,
  `restock_date` DATE NULL,
  `fill_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_food_fills1_idx` (`fill_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `Farm`.`chicks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Farm`.`chicks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fill_id` INT NULL,
  `amount` INT NULL,
  `mortality` INT NULL,
  `mortality_rate` FLOAT NULL,
  `daily_mortality` INT NULL,
  `sell_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chicks_fills1_idx` (`fill_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
